version: '2'

services:

    dj-app:
        extends:
            file: common.yml
            service: app
#        image:  decorist/zappalambda:cas-dev
        build:
            context: ../djTaskLine
            dockerfile: ./Dockerfile
        container_name: dj-app
#        command: runserver
        command: ["--socket", ":8000", "--stats", ":9191"]
        environment:
            DJANGO_SETTINGS_MODULE: dj_main.settings.dev
            ALLOWED_HOST: login.localhost
            UWSGI_INI: uwsgi.ini
            UWSGI_WORKERS: 2
            DJ_DEBUG: 1
        volumes:
            - ../djTaskLine/dj_app/:/dj_app
        ports:
            - "8000:8000"
            - "9191:9191"
        links:
            - postgresql
            - redis
##            - celery-worker
        depends_on:
            - postgresql
            - redis
##            - celery-worker

    ng-client-app:
        extends:
            file: ../ngTaskLine/docker-compose.yml
            service: serve
        build:
            context: ../ngTaskLine
            dockerfile: ./Dockerfile
        container_name: ng-client-app


    nginx:
        extends:
            file: common.yml
            service: proxy
        build:
            context: ../nginx
            dockerfile: ./Dockerfile
        container_name: nginx-http
        volumes:
            - ../nginx/config/conf.templ.local:/etc/nginx/conf.templ:ro
            - ../nginx/config/includes:/etc/nginx/includes:ro
#            - ../nginx/config/entrypoint.sh:/entrypoint.sh
            - ../djTaskLine/dj_app/collect:/var/www/collect:ro
        links:
            - dj-app
            - ng-client-app
        depends_on:
            - dj-app
            - ng-client-app
