version: '2'

services:

    dj-app:
        extends:
            file: common.yml
            service: app
#        image:  decorist/zappalambda:cas-dev
        build:
            context: ../djTasklLine
            dockerfile: ./Dockerfile
        container_name: dj-app
        command: runserver
#        command: ["--http", ":8000"]
        environment:
            DJANGO_SETTINGS_MODULE: dj_main.settings.dev
            RDS_HOSTNAME: mysql
            RDS_PORT: 3306
            RDS_DB_NAME: auth-client
            ALLOWED_HOST: login.localhost
            UWSGI_INI: uwsgi.ini
            UWSGI_WORKERS: 2
            DJ_DEBUG: 1
        volumes:
            - ../projectCAS/dj_app/:/dj_app
#        ports:
#            - "8000:8000"
#            - "9191:9191"
#        links:
#            - mysql
##            - redis
##            - celery-worker
#        depends_on:
#            - mysql
##            - redis
##            - celery-worker


#    nginx:
#        extends:
#            file: common.yml
#            service: proxy
#        container_name: nginx-http
#        volumes:
#            - ../projectCAS/nginx/conf.templ.http:/etc/nginx/conf.templ:ro
#            - ../projectCAS/nginx/entrypoint.sh:/entrypoint.sh
#            - ../projectCAS/nginx/conf.templ:/etc/nginx/conf.templ:ro
#            - ../projectCAS/dj_app/collect:/var/www/collect:ro
#            - ../projectCAS/nginx/includes:/etc/nginx/includes:ro
#        links:
#            - dj-app
