# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pt_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
