# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_line', '0002_auto_20170113_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pt_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='time_line.PTProfile'),
        ),
    ]
